name: Publish release

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [master]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/v') }}

    steps:
      - name: Download linux artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-and-build.yml
          name: scribblers-linux-x64

      - name: Download macos artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-and-build.yml
          name: scribblers-macos-x64

      - name: Download windows artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-and-build.yml
          name: scribblers-x64.exe

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            scribblers-linux-x64
            scribblers-macos-x64
            scribblers-windows-x64.exe
