name: Build

on: push

jobs:
  test-and-build:
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            binary_name: scribblers-linux-x64

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Build artifact
        shell: bash
        env:
          VERSION: "$(git describe --tags --dirty)"
        run: |
          echo "$VERSION"
