name: Build

on: push

jobs:
  test-and-build:
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            binary_name: scribblers-linux-x64

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Build artifact
        shell: bash
        run: |
          echo "${{ github.ref }}"
