name: Build

on: push

jobs:
  test-and-build:
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            binary_name: scribblers-linux-x64

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Run tests
        shell: bash
        run: |
          go test -race -covermode=atomic ./...

      - name: Build artifact
        shell: bash
        env:
          VERSION_A: ${{ github.head_ref }}
        run: |
          echo "$VERSION_A"
